### ISSUE TITLE
Package name mismatch between YOCTO project and NVD CVE database.

### ISSUE THREAD

**Issue by serhepopovych** [01org/meta-security-isafw#13]
Found at least for the kernel package:

In NVD CVE Linux Kernel product named as «linux_kernel» with versions in «X.Y.Z» format, while in YOCTO/OpenEmbedded it's name is «linux-yocto» and version «3.19.2+gitAUTOINC+XXXXXXXXXX_XXXXXXXXXX». Therefore check results for such mismatched packets is mean less.

One of the possible approaches to address this issue is to create version mapping between package name/version in YOCTO and package name/version in NVD CVE. Possibly by using package list from analyse_image() phase (or call to manifest2pkglist()).

**Comment by ereshetova** [comment]
Sure, I guess creating a mapping is possible, I am just wondering if there are any better ways. 
I will ask Yocto guys about this, also they might have a list of their exceptions already specified.

**Comment by ereshetova** [comment]
Actually while drinking more tea and finally waking up. The reason why kernel package is named differently for yocto is most likely because it is different. Yocto project maintains their own kernel and actually I guess in princple new CVEs cna be found just for yocto kernel and not upstream packaged linux_kernel package. So, in this case you might need to check CVEs for both: linux_kernel and linux-yocto. So, it is more like we need an additional list of packages to check. 

Does it make sense for you?

**Comment by serhepopovych** [comment]
Yes, I think checking both linux_kernel and linux-yocto makes sence. And yes, we probably need an additional list of packages to check.

**Comment by ereshetova** [comment]
And I have to fix the versions anyway by dropping the +git... prefix from them

**Comment by ereshetova** [comment]
I asked Yocto guys about it and it turns out they already have a solution for problem. DISTRO_PN_ALIAS variable can display the alternative names for each package (if exists) for other distros. I made a test run and able to get this kind of output for example for glib:

WARNING: alias name is Meego=glib2 Fedora=glib2 OpenSuSE=glib2 Ubuntu=glib2.0 Mandriva=glib2.0 Debian=glib2.0

I will try to implement the actual solution based on it this week.

**Comment by serhepopovych** [comment]
Really cool!!!
Waiting for this)

**Comment by ereshetova** [comment]
Ok, here is the pull request : https://github.com/01org/meta-security-isafw/pull/17 

There is an issue with at least one package output there. For some reason in Yocto an alias for 
opkg-utils is defined as "OSPDT upstream=git://git.yoctoproject.org/opkg-utils", which is against the syntax of other aliases and results in this wrong output:

git://git.yoctoproject.org/opkg-utils,0.1.8,,
OSPDT,0.1.8,,

I will file a bug to Yocto about this.

**Comment by ereshetova** [comment]
Actually it seems that many packages have this OSPDT thing and some have upstream. I think it might be just easier to filter them out... will fix now.

**Comment by ereshetova** [comment]
Pull request https://github.com/01org/meta-security-isafw/pull/17 updated

**Comment by serhepopovych** [comment]
Ok, I will try it in next few hours. Thanks for the effort to address this issue.

**Comment by ereshetova** [comment]
Closing this as pull request https://github.com/01org/meta-security-isafw/pull/17 is now merged
